version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
      deps:
        type: string
    docker:
      - image: python:<< parameters.python-version >>
    steps:
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.1.13 && ln -s $HOME/.poetry/bin/poetry /usr/local/bin/poetry
      - run: poetry env use << parameters.python-version >> && python -V
      - run: poetry install << parameters.deps >>
      - run: poetry run pytest
  linting:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run: curl -sSL https://install.python-poetry.org | python - --version 1.1.13 && ln -s $HOME/.local/bin/poetry /usr/local/bin/poetry
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run mypy

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-version:
                - "3.10"
                - "3.9"
                - "3.8"
                - "3.7"
              deps:
                - ""
                - "-E lxml"
      - linting
